import Mathlib.Logic.Relation
import Mathlib.Order.Preorder.Finite

/-!
# Concrete dependence-poset lemmas for heap decomposition

A heap is a labelled partially ordered set whose incompatible occurrences are
comparable and whose strict order is generated by those comparisons.  These
lemmas concern actual occurrence posets, not a formal power series or a numerical
recurrence.  Counting heaps also requires identifying labelled isomorphic posets;
this file does not silently count arbitrary occurrence numberings as different
heaps.
-/

namespace RootedKP

namespace Heaps

variable {P E : Type*} [PartialOrder E]

/-- The elementary comparisons that generate a heap's order. -/
def DependencyStep (R : P → P → Prop) (label : E → P) (x y : E) : Prop :=
  x < y ∧ R (label x) (label y)

/-- A labelled dependence poset.  Finiteness is imposed only where needed. -/
structure IsHeap (R : P → P → Prop) (label : E → P) : Prop where
  comparable : ∀ x y, R (label x) (label y) → x ≤ y ∨ y ≤ x
  generated : ∀ x y, x < y → Relation.TransGen (DependencyStep R label) x y

theorem dependency_reflTransGen_le {R : P → P → Prop} {label : E → P}
    {x y : E} (h : Relation.ReflTransGen (DependencyStep R label) x y) : x ≤ y := by
  induction h with
  | refl => exact le_rfl
  | tail _ hstep ih => exact ih.trans hstep.1.le

/-- A reflexive transitive relation containing the elementary dependence
comparisons contains the entire heap order. -/
theorem order_generated_by_dependencies {R : P → P → Prop} {label : E → P}
    (H : IsHeap R label) (S : E → E → Prop)
    (hsrefl : ∀ x, S x x) (hstrans : ∀ x y z, S x y → S y z → S x z)
    (hsstep : ∀ x y, DependencyStep R label x y → S x y)
    {x y : E} (hxy : x ≤ y) : S x y := by
  by_cases heq : x = y
  · subst y
    exact hsrefl x
  · have hpath := H.generated x y (lt_of_le_of_ne hxy heq)
    clear hxy heq
    induction hpath with
    | single h => exact hsstep _ _ h
    | tail _ h ih => exact hstrans _ _ _ ih (hsstep _ _ h)

/-- A dependence chain between points of a convex set stays within that set. -/
theorem dependency_path_in_subset {R : P → P → Prop} {label : E → P}
    (S : E → Prop)
    (hconvex : ∀ {x y z}, S x → S z → x ≤ y → y ≤ z → S y)
    {x y : E} (hpath : Relation.TransGen (DependencyStep R label) x y)
    (hx : S x) (hy : S y) :
    Relation.TransGen (DependencyStep R (fun z : {z // S z} => label z))
      ⟨x, hx⟩ ⟨y, hy⟩ := by
  revert hy
  induction hpath with
  | single h =>
      intro hy
      exact .single h
  | @tail b c hpath hstep ih =>
      intro hc
      have hb : S b := hconvex hx hc
        (dependency_reflTransGen_le hpath.to_reflTransGen) hstep.1.le
      exact .tail (ih hb) hstep

/-- Restriction to an order-convex set is again a heap. -/
theorem isHeap_subtype_of_convex {R : P → P → Prop} {label : E → P}
    (H : IsHeap R label) (S : E → Prop)
    (hconvex : ∀ {x y z}, S x → S z → x ≤ y → y ≤ z → S y) :
    IsHeap R (fun z : {z // S z} => label z) where
  comparable x y h := H.comparable x y h
  generated x y h :=
    dependency_path_in_subset S hconvex (H.generated x y h) x.property y.property

/-- Self-incompatibility makes the labels of distinct minimal occurrences distinct. -/
theorem minimal_label_injective {R : P → P → Prop} {label : E → P}
    (H : IsHeap R label) (hself : ∀ p, R p p) {x y : E}
    (hx : IsMin x) (hy : IsMin y) (hlabel : label x = label y) : x = y := by
  have hdep : R (label x) (label y) := by rw [← hlabel]; exact hself _
  rcases H.comparable x y hdep with h | h
  · exact le_antisymm h (hy h)
  · exact le_antisymm (hx h) h

/-- Every occurrence of a finite poset has a minimal ancestor. -/
theorem exists_minimal_ancestor [Finite E] (x : E) :
    ∃ m, IsMin m ∧ m ≤ x := by
  obtain ⟨m, hm⟩ := (Set.toFinite {m : E | m ≤ x}).exists_minimal ⟨x, le_rfl⟩
  refine ⟨m, ?_, hm.1⟩
  intro y hym
  exact hm.2 (hym.trans hm.1) hym

variable [LinearOrder P]

/-- Assign an occurrence the largest label of one of its minimal ancestors. -/
structure MinimalAncestorLabelling (label : E → P) where
  owner : E → P
  realized : ∀ x, ∃ m, IsMin m ∧ m ≤ x ∧ label m = owner x
  greatest : ∀ x m, IsMin m → m ≤ x → label m ≤ owner x

theorem exists_largest_minimal_ancestor [Finite E] (label : E → P) (x : E) :
    ∃ m, IsMin m ∧ m ≤ x ∧ ∀ r, IsMin r → r ≤ x → label r ≤ label m := by
  obtain ⟨m, hm, hmx⟩ := exists_minimal_ancestor x
  obtain ⟨r, hr⟩ := Set.Finite.exists_maximalFor label
    {r : E | IsMin r ∧ r ≤ x} (Set.toFinite _) ⟨m, hm, hmx⟩
  refine ⟨r, hr.1.1, hr.1.2, ?_⟩
  intro s hs hsx
  by_cases h : label r ≤ label s
  · exact hr.2 ⟨hs, hsx⟩ h
  · exact (lt_of_not_ge h).le

/-- The canonical owner labelling exists for every finite occurrence poset. -/
noncomputable def largestMinimalAncestorLabelling [Finite E] (label : E → P) :
    MinimalAncestorLabelling label where
  owner x := label (Classical.choose (exists_largest_minimal_ancestor label x))
  realized x := by
    let m := Classical.choose (exists_largest_minimal_ancestor label x)
    have hm := Classical.choose_spec (exists_largest_minimal_ancestor label x)
    exact ⟨m, hm.1, hm.2.1, rfl⟩
  greatest x m hm hmx :=
    (Classical.choose_spec (exists_largest_minimal_ancestor label x)).2.2 m hm hmx

namespace MinimalAncestorLabelling

variable {label : E → P} (A : MinimalAncestorLabelling label)

theorem monotone : Monotone A.owner := by
  intro x y hxy
  obtain ⟨m, hm, hmx, hlabel⟩ := A.realized x
  rw [← hlabel]
  exact A.greatest y m hm (hmx.trans hxy)

theorem owner_of_minimal {m : E} (hm : IsMin m) : A.owner m = label m := by
  obtain ⟨r, hr, hrm, hlabel⟩ := A.realized m
  have heq : r = m := le_antisymm hrm (hm hrm)
  simpa [heq] using hlabel.symm

/-- Each owner class is order-convex. -/
theorem convex {x y z : E} (hxy : x ≤ y) (hyz : y ≤ z)
    (howner : A.owner x = A.owner z) : A.owner y = A.owner x := by
  apply le_antisymm
  · simpa [howner] using A.monotone hyz
  · exact A.monotone hxy

/-- The selected minimal occurrence lies below every occurrence in its owner class. -/
theorem group_root_le {R : P → P → Prop} (H : IsHeap R label) (hself : ∀ p, R p p)
    {m x : E} (hm : IsMin m) (hlabel : label m = A.owner x) : m ≤ x := by
  obtain ⟨r, hr, hrx, hrlabel⟩ := A.realized x
  have heq : m = r := minimal_label_injective H hself hm hr (hlabel.trans hrlabel.symm)
  exact heq ▸ hrx

/-- Each owner group, with the induced order and labels, is itself a heap. -/
theorem group_isHeap {R : P → P → Prop} (H : IsHeap R label) (p : P) :
    IsHeap R (fun z : {z // A.owner z = p} => label z) := by
  apply isHeap_subtype_of_convex H
  intro x y z hx hz hxy hyz
  exact (A.convex hxy hyz (hx.trans hz.symm)).trans hx

/-- Every nonempty owner group has a least occurrence with that owner's label.
Thus its induced heap is a pyramid, not merely a connected heap. -/
theorem group_has_least {R : P → P → Prop} (H : IsHeap R label)
    (hself : ∀ p, R p p) {p : P} (hne : ∃ x, A.owner x = p) :
    ∃ m : {z // A.owner z = p}, label m = p ∧ ∀ x : {z // A.owner z = p}, m ≤ x := by
  obtain ⟨x, hx⟩ := hne
  obtain ⟨m, hm, _, hlabel⟩ := A.realized x
  have hmp : label m = p := hlabel.trans hx
  have howner : A.owner m = p := (A.owner_of_minimal hm).trans hmp
  refine ⟨⟨m, howner⟩, hmp, ?_⟩
  intro y
  exact A.group_root_le H hself hm (hmp.trans y.property.symm)

/-- An incompatible comparison between owner classes cannot point backwards.
This is the key reconstruction lemma for concatenating the classes in order. -/
theorem no_backward_dependency {R : P → P → Prop} (H : IsHeap R label)
    {x y : E} (howner : A.owner x < A.owner y) (hdep : R (label x) (label y)) :
    x ≤ y := by
  rcases H.comparable x y hdep with h | h
  · exact h
  · exact False.elim ((not_le_of_gt howner) (A.monotone h))

/-- The comparisons used when the owner groups are concatenated in increasing
order: within-group comparisons, and forward inter-group dependencies. -/
def ReconstructedStep (R : P → P → Prop) (x y : E) : Prop :=
  (A.owner x = A.owner y ∧ x < y) ∨
    (A.owner x < A.owner y ∧ R (label x) (label y))

/-- Concatenation of the owner groups reconstructs the original heap order.
Consequently the groups lose no dependence-order information. -/
theorem reconstruction {R : P → P → Prop} (H : IsHeap R label) {x y : E} :
    Relation.ReflTransGen (A.ReconstructedStep R) x y ↔ x ≤ y := by
  constructor
  · intro h
    induction h with
    | refl => exact le_rfl
    | tail _ hstep ih =>
        apply ih.trans
        rcases hstep with h | h
        · exact h.2.le
        · exact A.no_backward_dependency H h.1 h.2
  · intro hxy
    apply order_generated_by_dependencies H (Relation.ReflTransGen (A.ReconstructedStep R))
      (fun _ => .refl) (fun _ _ _ h₁ h₂ => h₁.trans h₂) ?_ hxy
    intro u v hstep
    apply Relation.ReflTransGen.single
    rcases (A.monotone hstep.1.le).eq_or_lt with heq | hlt
    · exact Or.inl ⟨heq, hstep.1⟩
    · exact Or.inr ⟨hlt, hstep.2⟩

end MinimalAncestorLabelling

omit [LinearOrder P] in
/-- Removing the least occurrence of a heap leaves only incompatible minimal
occurrences.  This supplies the neighbour restriction in the product recursion. -/
theorem new_minimum_incompatible {R : P → P → Prop} {label : E → P}
    (H : IsHeap R label) {root x : E} (hroot : ∀ y, root ≤ y)
    (hne : root ≠ x)
    (hminimal : ∀ y, y ≠ root → y ≤ x → x ≤ y) : R (label root) (label x) := by
  have hlt : root < x := lt_of_le_of_ne (hroot x) hne
  obtain ⟨y, hfirst, hrest⟩ := Relation.TransGen.head'_iff.mp (H.generated root x hlt)
  have hyx : y ≤ x := dependency_reflTransGen_le hrest
  have hyn : y ≠ root := ne_of_gt hfirst.1
  have heq : y = x := le_antisymm hyx (hminimal y hyn hyx)
  simpa [heq] using hfirst.2

end Heaps
end RootedKP
